# Generated by Django 4.0.5 on 2022-06-13 17:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0004_alter_dataset_last_update_dstcolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dstcolumn',
            name='pos_choise',
        ),
        migrations.AddField(
            model_name='dstcolumn',
            name='pos_choice',
            field=models.BooleanField(default=False, verbose_name='Active Postfix'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 17, 18, 54, 65921, tzinfo=utc), verbose_name='Last Update Dataset'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='column_number',
            field=models.IntegerField(default=0, verbose_name='Column Sequence'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.dataset'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='pos_value',
            field=models.CharField(max_length=5, verbose_name='Value Postfix'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='pre_choice',
            field=models.BooleanField(default=False, verbose_name='Active Prefix'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='pre_value',
            field=models.CharField(max_length=5, verbose_name='Value Prefix'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
