# Generated by Django 4.0.5 on 2022-06-20 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0011_alter_dataset_last_update_alter_keyword_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dstcolumn',
            name='column_delete',
            field=models.BooleanField(default=False, verbose_name='Delete Column?'),
        ),
        migrations.AddField(
            model_name='dstcolumn',
            name='column_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Column Name'),
        ),
        migrations.AddField(
            model_name='dstcolumn',
            name='replace_terms',
            field=models.BooleanField(default=False, verbose_name='Run replacement term?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 14, 30, 42, 588309, tzinfo=utc), verbose_name='Last Update Dataset'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Active Rule?'),
        ),
    ]
