# Generated by Django 4.0.5 on 2022-06-20 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0012_dstcolumn_column_delete_dstcolumn_column_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dstcolumn',
            name='column_delete',
        ),
        migrations.AddField(
            model_name='keyword',
            name='commute',
            field=models.BooleanField(default=False, verbose_name='Commute?'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 18, 50, 19, 567471, tzinfo=utc), verbose_name='Last Update Dataset'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='pos_choice',
            field=models.BooleanField(default=False, verbose_name='Postfix?'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='pre_choice',
            field=models.BooleanField(default=False, verbose_name='Prefix?'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='replace_terms',
            field=models.BooleanField(default=False, verbose_name='Replacement?'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Active?'),
        ),
    ]
