# Generated by Django 4.0.5 on 2022-06-20 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0013_remove_dstcolumn_column_delete_keyword_commute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dstcolumn',
            name='replace_terms',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 21, 37, 21, 833421, tzinfo=utc), verbose_name='Last Update Dataset'),
        ),
    ]
