# Generated by Django 4.0.5 on 2022-06-21 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0015_remove_dataset_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyge',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='wfcontrol',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 18, 22, 19, 807644, tzinfo=utc), verbose_name='Last Update Dataset'),
        ),
    ]
