# Generated by Django 4.0.5 on 2022-06-21 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0016_alter_keyge_description_alter_wfcontrol_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfcontrol',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 19, 17, 31, 775301, tzinfo=utc), verbose_name='Last Update Dataset'),
        ),
    ]
