# Generated by Django 4.0.5 on 2022-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0017_alter_wfcontrol_last_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.AlterField(
            model_name='wfcontrol',
            name='last_update',
            field=models.DateTimeField(verbose_name='Last Update Dataset'),
        ),
    ]
