# Generated by Django 4.0.5 on 2022-06-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0019_remove_dstcolumn_pos_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefixOpc',
            fields=[
                ('pre_value', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Value Prefix')),
            ],
        ),
        migrations.RemoveField(
            model_name='dstcolumn',
            name='pre_choice',
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='pre_value',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='ge.prefixopc', verbose_name='Prefix'),
        ),
    ]
