# Generated by Django 4.0.5 on 2022-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0020_prefixopc_remove_dstcolumn_pre_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dstcolumn',
            name='pre_choice',
            field=models.BooleanField(default=False, verbose_name='Prefix?'),
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='pre_value',
            field=models.CharField(blank=True, max_length=5, verbose_name='Value Prefix'),
        ),
    ]
