# Generated by Django 4.0.5 on 2022-06-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0021_dstcolumn_pre_choice_alter_dstcolumn_pre_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dstcolumn',
            name='pre_choice',
        ),
        migrations.AlterField(
            model_name='dstcolumn',
            name='pre_value',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='ge.prefixopc', verbose_name='Prefix'),
        ),
    ]
