# Generated by Django 4.0.5 on 2022-08-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0027_alter_wfcontrol_source_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfcontrol',
            name='chk_commute',
        ),
        migrations.RemoveField(
            model_name='wfcontrol',
            name='chk_mapreduce',
        ),
        migrations.AddField(
            model_name='wfcontrol',
            name='chk_map',
            field=models.BooleanField(default=False, verbose_name='Map Processed'),
        ),
        migrations.AddField(
            model_name='wfcontrol',
            name='chk_reduce',
            field=models.BooleanField(default=False, verbose_name='Reduce Processed'),
        ),
    ]
