# Generated by Django 4.0.5 on 2022-06-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0007_rename_key_keyword_key_alter_dataset_last_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key',
            new_name='Keyge',
        ),
        migrations.RenameField(
            model_name='keyge',
            old_name='key',
            new_name='keyge',
        ),
        migrations.RenameField(
            model_name='keylink',
            old_name='key1',
            new_name='keyge1',
        ),
        migrations.RenameField(
            model_name='keylink',
            old_name='key2',
            new_name='keyge2',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='key',
            new_name='keyge',
        ),
        migrations.RenameField(
            model_name='wordmap',
            old_name='key1',
            new_name='keyge1',
        ),
        migrations.RenameField(
            model_name='wordmap',
            old_name='key2',
            new_name='keyge2',
        ),
    ]
