# Generated by Django 4.0.5 on 2022-06-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0008_rename_key_keyge_rename_key_keyge_keyge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True)),
                ('version', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('size', models.IntegerField(default=0)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.database')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.dataset')),
            ],
        ),
    ]
