# Generated by Django 4.0.5 on 2022-06-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0009_logscollector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logscollector',
            name='database',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='logscollector',
            name='dataset',
            field=models.CharField(max_length=200),
        ),
    ]
