# Generated by Django 4.0.5 on 2022-06-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0012_rename_dataset_wordmap_dataset_alter_wordmap_keyge1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmap',
            name='id',
        ),
        migrations.AddField(
            model_name='wordmap',
            name='cword',
            field=models.CharField(default='x', max_length=45, primary_key=True, serialize=False),
        ),
    ]
