# Generated by Django 4.0.5 on 2022-06-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0013_remove_wordmap_id_wordmap_cword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keylink',
            name='id',
        ),
        migrations.AlterField(
            model_name='keylink',
            name='ckey',
            field=models.CharField(default='x', max_length=45, primary_key=True, serialize=False),
        ),
    ]
