# Generated by Django 4.0.5 on 2022-06-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0014_remove_keylink_id_alter_keylink_ckey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keylink',
            name='ccat',
        ),
        migrations.RemoveField(
            model_name='keylink',
            name='cgrp',
        ),
        migrations.RemoveField(
            model_name='keylink',
            name='database',
        ),
    ]
