# Generated by Django 4.0.5 on 2022-06-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0016_remove_blacklist_id_remove_keyword_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.keyge'),
        ),
    ]
